### ISSUE TITLE
Spelling Error

### ISSUE THREAD

**Issue by nprowler** [cinhcet/node-red-contrib-mpd#4]
Line 67  in mpd.js has a spelling error "Connetcion " should be "Connection" ?

**Comment by cinhcet** [comment]
thanks! If you find more before I publish a new version to npm, I would be happy (or not, because then there are no spelling errors :-))
8e7e461

**Comment by nprowler** [comment]
lol no worries I am a poor speller but that stood out. [😊]

Great work on this node. I use it in my home automation dashboard.


Thanks for making it for us.


Steve


________________________________

**Comment by cinhcet** [comment]
:-)

**Comment by nprowler** [comment]
I see that you where working on some home automation. How are you making out with it?

I started to build one over a year ago and was way over my head. But have come a long way.

Not being a programmer by nature just as a hobbyist I had to learn a tonne, And still am hence why I was looking at your code to try and learn. [😊]

I have a nice setup now. 4 esp8266 doing temperature, Humidity and motion. Sending data via MQTT. 4 433mhz wall sockets controlled by a cheap 433mhz transmitter

radio. And controlled via Node-Red. I started to build the web interface via websockets like you in the early days but since Nod-Red-Dashboard  came out

that all changed. I now have a feature list that is starting to get crazy. Poor Raspberry Pi its getting close to what it can handle with Node-red. Like memory. lol

Anyways Why I am telling you this is I am curious on how other people are implementing there own home automation setups. Like what kind of feature you find very useful?

Some of the ones I use are.

Weather

Weather alerts sent to phone.

Owntracks for tracking with Google maps overlay. Zones (Home, Work, Away)

Music info from volumio player.

Motion tracking

Temperature reading around the house

 Virtual light switches

house chat with speech

Traffic conditions shown on a map of the city.

Estimated time to drive to work updated every 5 mins in the morning


These are just some of them and are all nicely displayed on Node-Red-Dashboard on a few tablets around the house.


Anyways sorry to bother you with this I am just curious if you have continued working on yours and what cool features you might have.

I am still a bad programmer but still learning.


You do not need to reply to this message if you don't want to chat about it.

Just throwing it out there.


Steve


________________________________

**Comment by cinhcet** [comment]
Hi, that other repository is quite old, I think I should delete it, it was just a little test. 

I dont think that this github issue is a good place to discuss that. You could send me an email and we can continue there. My email should be in the package.json I think..
