### ISSUE TITLE
play x command one out from that entered in terminal

### ISSUE THREAD

**Issue by MikePRoberts** [cinhcet/node-red-contrib-mpd#5]
I have to send "play 0" to MPD out in order to get the first track in a playlist to play.
In terminal I enter: mpc play 1 for the first track
Would it be better to have these consistent?
Thank you.  I am using your nodes for an internet radio/music player that I will write up on instructables.com
Mike

**Comment by cinhcet** [comment]
this node adheres (hopefully :-P) to the mpd protocol, in which the first song has id 0. So the tool that is inconsistent is the mpc command line client. A general advice: The mpc tool does not use and/or support all the commands from the mpd reference https://www.musicpd.org/doc/protocol/command_reference.html
So you have to ask https://github.com/MusicPlayerDaemon/mpc for more consistency.

I'm looking forward to your instructable! I'm happy that someone uses my node :-)

**Comment by MikePRoberts** [comment]
Thank you for your reply.  I agree.  The discrepancy is between mpc and mpd!  Thank you for your work here.  I have been blown over by the capability of Node Red and the value of the contributions.  With your node I don't need a display for an internet radio/music system as suddenly ones smartphone becomes a universal remote control.
